Feature: ["feature/*", "feat/*"]
Bugfix: ["fix/*", "bugfix/*"]
Server: ["server/*", "Server/*"]
Testing: ["testing/*", "test/*"]
documentation: ["documentation/*", "docs/*"]
Website: ["website/*", "Website/*"]