name: Labeler
on:
  pull_request:
    types:
      - "opened"

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/labeler.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"